### ISSUE TITLE
Version 10 Fetch new version is kinda breaking everything.

### ISSUE THREAD

**Issue by jkeruzec** [masylum/mobx-rest#117]
Hi,

I'm openning a discussion here for the new version 10,

new version 10 with promise returned directly and async/await applied to fetch is breaking everything inside the code.

We can no longer user fetch like we did before and even the new version is not working perfectly as it is.

I'm staying with version 9 for the moment, as it is a long work to transform everything ....

**Comment by masylum** [comment]
Hi!

We are aware that the change is pretty much a breaking change (hence the major version).
We've done it because the patterns that emerged from having the `Request` object were very error-prone. By returning the promise, now we leave it to the application to track the loading state. By maintaining Factorial we've seen that is more consistent with how other asynchronous processes work and less error-prone. There were also some type and debugging implications on having the "promise-like" hack.
