### ISSUE TITLE
Specifying default values for Model attributes?

### ISSUE THREAD

**Issue by jzaefferer** [masylum/mobx-rest#22]
Since computed properties based on attributes throw exceptions when those attributes don't exist, I was looking for a way to specify default values for a Model's attributes. I didn't find anything in the docs or examples. I guess I could override the constructor a mix in defaults with an `Object.assign` call.

Is there any recommendation for that? What are users of this library doing?

**Comment by masylum** [comment]
We made the library a little bit strict because we think is good practice for REST APIs to keep predictable schemas. If that's not the case (for instance, given the current user some fields may not be visible) you can use the `has` method to check the existence of that attribute.

I think default attributes can be useful in any case. Feel free to open a PR!

**Comment by jzaefferer** [comment]
Looks like overriding the constructor works fine:
```
class User extends Model {
  constructor(attributes) {
    super(Object.assign({
      token: null,
      email_verified: false,
    }, attributes))
  }
}
```
Could add that as an example to the docs for Model#attributes, along with the disclaimer for using `has()`.

What do you think?

**Comment by masylum** [comment]
Adding it to the docs :+1:

**Comment by masylum** [comment]
https://github.com/masylum/mobx-rest/commit/67b85ac7a397b14b0630ce2e72b5e0f6ec578e90
