### ISSUE TITLE
calling destroy on model Uncaught (in promise)

### ISSUE THREAD

**Issue by jkeruzec** [masylum/mobx-rest#47]
I'm trying to destroy a model from a collection I have using destroy method.

```js
 deleteProject(value) {
        // Delete project
        projectsCollection.get(value).destroy({optimistic: false});
        projectsCollection.remove([value]);
    }
```

Destroy is done well on my Rest call that return a 200 OK response.

![image](https://user-images.githubusercontent.com/3499632/42040400-cefcef40-7aef-11e8-840d-6d0ca1ed3bf9.png)

But console display an error message : 
```js
asyncToGenerator.js:20 Uncaught (in promise) {}
```
error is empty and I don't get it ... 

It is not a blocker for me but it's not very clean either.. 

Thanks for your help !

**Comment by jkeruzec** [comment]
I explore a bit more this issue and found that DELETE order must return a JSON response in order to not reject the call.... 

In some normalization, a 200 OK response on a DELETE order can send a description status in body response.
I also read that a 204 No Content on a DELETE order send an empty body

Some information... :
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

**Comment by geclos** [comment]
Hi @jkeruzec, 

it's been a long time since this issue was reported. Did you manage to fix it by yourself? If not, which adapter are you experiencing this issue with? 

We use `mobx-rest` with the jQuery adapter extensively at [Factorial](https://factorialhr.com/) with an API that returns DELETE 204 without body and we haven't been able to reproduce this issue.
